time_tracker/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    path('', HomeView.as_view(), name='homepage'),
    path('tracker/', TrackerHomeView.as_view(), name='tracker-home'),
    path('tracker/time-log', TimeLogListView.as_view(), name='time-log-list'),
    path('tracker/project/create', ProjectCreateView.as_view(), name='project-create'),
    path('tracker/project/<slug:slug>', ProjectDetailView.as_view(), name='project-info'),
    path('tracker/project/<slug:slug>/edit', ProjectUpdateView.as_view(), name='project-edit'),
    path('tracker/project/<slug:slug>/task/create', TaskCreateView.as_view(), name='task-create'),
    path('tracker/project/<slug:slug>/task/<int:task_id>', TaskDetailView.as_view(), name='task-info'),
    path('tracker/project/<slug:slug>/task/<int:task_id>/edit', TaskUpdateView.as_view(), name='task-edit'),
]

ttr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('time_tracker.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tinymce/', include('tinymce.urls')),

]

time_tracker/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from tinymce import models as tinymce_models
from django.template.defaultfilters import slugify


def get_image_path(instance, filename):
    return os.path.join('user_avatars', str(instance.user.id), filename)


class Developer(models.Model):
    user = models.ForeignKey(
        User,
        null=True,
        on_delete=models.SET_NULL
    )
    birth_date = models.DateField(null=True, blank=True)
    position = models.CharField(max_length=128, blank=True)
    avatar = models.FileField(upload_to=get_image_path, blank=True)

    def __str__(self):
        return self.user.username


class Project(models.Model):
    name = models.CharField(max_length=128)
    description = tinymce_models.HTMLField()
    slug = models.SlugField(max_length=192)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Project, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Task(models.Model):
    PRIORITY_TYPE = (
        ('N', 'Normal'),
        ('H', 'High'),
        ('U', 'Urgent')
    )

    TASK_TYPE = (
        ('F', 'Feature'),
        ('B', 'Bug'),
    )
    subject = models.CharField(max_length=128)
    description = tinymce_models.HTMLField()
    date_start = models.DateField()
    date_stop = models.DateField()
    kind = models.CharField(max_length=1, choices=TASK_TYPE, default='F')
    priority = models.CharField(max_length=1, choices=PRIORITY_TYPE, default='N')
    hours = models.FloatField()
    implementer = models.ForeignKey(Developer, null=True, on_delete=models.SET_NULL, related_name='task_implementer')
    creator = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='task_creator')
    project = models.ForeignKey(Project, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.subject


class Comment(models.Model):
    comment = models.TextField()
    createdAt = models.DateTimeField(auto_now_add=True, null=True)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    task = models.ForeignKey(Task, null=True, on_delete=models.SET_NULL)


class Log(models.Model):
    hours = models.FloatField()
    comment = models.TextField()
    task = models.ForeignKey(Task, null=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

time_tracker/forms.py
from django import forms
from .models import Comment, Log, Task, Project


class AddCommentToTaskForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'


class AddTimeToTaskForm(forms.ModelForm):
    class Meta:
        model = Log
        fields = '__all__'


class CreateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('name', 'description')


class EditTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EditTaskForm, self).__init__(*args, **kwargs)
        self.fields['creator'].widget.attrs['disabled'] = True
        self.fields['creator'].required = False

    def clean_creator(self):
        if self.instance and self.instance.pk:
            return self.instance.creator
        else:
            return self.cleaned_data['creator']

time_tracker/views.py
from django.conf import settings
from django.dispatch import receiver
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, redirect, get_object_or_404
from time_tracker.models import Project, Task, Log, Developer, Comment
from django.views.generic import View, TemplateView, ListView, CreateView, DetailView, UpdateView
from time_tracker.forms import CreateTaskForm, EditTaskForm, AddTimeToTaskForm, AddCommentToTaskForm, ProjectForm


@receiver(pre_save, sender=Task)
def task_send_message(instance, sender, **kwargs):
    try:
        old = sender.objects.get(pk=instance.pk)
    except sender.DoesNotExist:
        pass
    else:
        html = get_template('email/email.html')
        d = {'old': old, 'new': instance}

        subject, from_email, to = 'Changed task', settings.EMAIL_HOST_USER, [old.creator.email,
                                                                             instance.implementer.user.email]
        html_content = html.render(d)
        msg = EmailMultiAlternatives(subject, "text_content", from_email, to)
        msg.attach_alternative(html_content, "text/html")
        msg.send()


class HomeView(TemplateView):
    template_name = 'index.html'


class TimeLogListView(ListView):
    model = Log
    template_name = 'list/log_index.html'
    context_object_name = 'logs'


class TrackerHomeView(View):

    def get(self, request, *args, **kwargs):
        if request.user.is_superuser:
            projects = Project.objects.all()
        else:
            dev = Developer.objects.get(user__username=request.user.username)
            projects_id = Task.objects.filter(implementer=dev).all()
            projects = Project.objects.filter(pk__in=[x.project.pk for x in projects_id])

        return render(request, 'tracker/tracker_home.html', {'projects': projects})


class ProjectDetailView(DetailView):
    model = Project
    template_name = 'tracker/project/project_info.html'
    context_object_name = 'project'
    calc_time = time = 0

    def set_time(self, tasks):
        for task in tasks:
            self.calc_time += task.hours
            for l in Log.objects.filter(task_id=task.id):
                self.time += float(l.hours)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tasks = Task.objects.filter(project__slug=self.object.slug)
        self.set_time(tasks)
        context['tasks'] = tasks
        context['hours'] = self.time
        context['caclTime'] = self.calc_time
        return context


class TaskDetailView(DetailView):
    model = Task
    template_name = 'tracker/task/task_info.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Task, id=self.kwargs.get('task_id'))

    def post(self, request, *args, **kwargs):
        f_time = AddTimeToTaskForm(request.POST, prefix='time')
        f_comment = AddCommentToTaskForm(request.POST, prefix='comment')

        if f_time.is_valid():
            f_time.save()
            return redirect('task-info', slug=self.kwargs.get('slug'), task_id=self.kwargs.get('task_id'))

        if f_comment.is_valid():
            f_comment.save()
            return redirect('task-info', slug=self.kwargs.get('slug'), task_id=self.kwargs.get('task_id'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        spent_time = 0
        project = Project.objects.get(slug=self.kwargs.get('slug'))
        comments = Comment.objects.filter(task_id=self.kwargs.get('task_id')).order_by('-createdAt')
        time = Log.objects.filter(task_id=self.kwargs.get('task_id'))
        for t in time:
            spent_time += t.hours

        context['f_time'] = AddTimeToTaskForm(
            initial={'task': self.get_object(), 'user': User.objects.get(username=self.request.user)},
            prefix='time')
        context['f_comment'] = AddCommentToTaskForm(
            initial={'task': self.get_object(), 'author': User.objects.get(username=self.request.user)},
            prefix='comment')
        context['project'] = project
        context['comments'] = comments
        context['time_list'] = time
        context['spent_time'] = spent_time

        return context


class TaskUpdateView(UpdateView):
    model = Task
    template_name = 'tracker/task/edit_task_info.html'
    form_class = EditTaskForm

    def get_object(self, queryset=None):
        return get_object_or_404(Task, id=self.kwargs.get('task_id'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = Project.objects.get(slug=self.kwargs.get('slug'))
        return context


class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectForm
    template_name = 'tracker/project/create_project.html'
    success_url = reverse_lazy('tracker-home')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(ProjectCreateView, self).dispatch(*args, **kwargs)


class ProjectUpdateView(UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = 'tracker/project/edit_project.html'
    success_url = reverse_lazy('tracker-home')

    def get_object(self, queryset=None):
        return get_object_or_404(Project, slug=self.kwargs.get('slug'))

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(ProjectUpdateView, self).dispatch(*args, **kwargs)


class TaskCreateView(CreateView):
    model = Task
    form_class = CreateTaskForm
    template_name = 'tracker/task/create_task.html'
    success_url = reverse_lazy('tracker-home')

    def get_initial(self):
        project = Project.objects.get(slug=self.kwargs.get('slug'))
        return {'project': project, 'creator': self.request.user}

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(TaskCreateView, self).dispatch(*args, **kwargs)

time_tracker/templates/tracker/task/create_task.html
{% extends 'tracker/tracker_home.html' %}

{% load widget_tweaks %}
{% load static %}

{% block title %}Create task for {{ project.name }} project{% endblock %}

{% block brdc-links %}
    <li class="breadcrumb-item"><a href="{% url 'homepage' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'tracker-home' %}">Tracker</a></li>
    <li class="breadcrumb-item active" aria-current="page">Create task for {{ project.name }} project</li>
{% endblock %}

{% block add_to_head %}
    <script type="text/javascript" src="{% static "tiny_mce/tiny_mce.js" %}"></script>
    {{ form.media }}
{% endblock %}

{% block content %}
    <h1 class="h2">Create task</h1>
    </div>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    <div class="row">
        <div class="col-md-12">
            <form method="post">
                {% csrf_token %}
                {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field }}
                {% endfor %}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="{{ form.subject.id_for_label }}">Subject</label>
                        {{ form.subject|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ form.description.id_for_label }}">Description</label>
                    {{ form.description|add_class:"form-control" }}
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="{{ form.date_start.id_for_label }}">Date start</label>
                        {{ form.date_start|add_class:"form-control"|attr:"type:date" }}
                    </div>
                    <div class="form-group col-md-6">
                        <label for="{{ form.date_stop.id_for_label }}">Date stop</label>
                        {{ form.date_stop|add_class:"form-control"|attr:"type:date" }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="{{ form.kind.id_for_label }}">Kind</label>
                        {{ form.kind|add_class:"form-control" }}
                    </div>
                    <div class="form-group col-md-4">
                        <label for="{{ form.priority.id_for_label }}">Priority</label>
                        {{ form.priority|add_class:"form-control" }}
                    </div>
                    <div class="form-group col-md-4">
                        <label for="{{ form.hours.id_for_label }}">Hours</label>
                        {{ form.hours|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="{{ form.implementer.id_for_label }}">Implementer</label>
                        {{ form.implementer|add_class:"form-control" }}
                    </div>
                    <div class="form-group col-md-4">
                        <label for="{{ form.creator.id_for_label }}">Creator</label>
                        {{ form.creator|add_class:"form-control" }}
                    </div>
                    <div class="form-group col-md-4">
                        <label for="{{ form.project.id_for_label }}">Project</label>
                        {{ form.project|add_class:"form-control" }}
                    </div>
                </div>
                <br>
                <button class="btn btn-secondary btn-lg btn-block" type="submit">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

time_tracker/templates/tracker/task/edit_task_info.html
{% extends 'tracker/tracker_home.html' %}

{% load static %}
{% load widget_tweaks %}

{% block title %}Edit {{ task.subject }} task{% endblock %}


{% block add_to_head %}
    <script type="text/javascript" src="{% static "tiny_mce/tiny_mce.js" %}"></script>
    {{ form.media }}
{% endblock %}

{% block brdc-links %}
    <li class="breadcrumb-item"><a href="{% url 'homepage' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'tracker-home' %}">Tracker</a></li>
    <li class="breadcrumb-item active" aria-current="page">Edit {{ task.subject }} task</li>
{% endblock %}


{% block content %}
    <h1 class="h2">Edit task</h1>
    </div>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    <div class="row">
        <div class="col-md-12">
            <form method="post">
                {% csrf_token %}
                {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field }}
                {% endfor %}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="{{ form.subject.id_for_label }}">Subject</label>
                        {{ form.subject|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ form.description.id_for_label }}">Description</label>
                    {{ form.description|add_class:"form-control" }}
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="{{ form.date_start.id_for_label }}">Date start</label>
                        {{ form.date_start|add_class:"form-control"|attr:"type:date" }}
                    </div>
                    <div class="form-group col-md-6">
                        <label for="{{ form.date_stop.id_for_label }}">Date stop</label>
                        {{ form.date_stop|add_class:"form-control"|attr:"type:date" }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="{{ form.kind.id_for_label }}">Kind</label>
                        {{ form.kind|add_class:"form-control" }}
                    </div>
                    <div class="form-group col-md-4">
                        <label for="{{ form.priority.id_for_label }}">Priority</label>
                        {{ form.priority|add_class:"form-control" }}
                    </div>
                    <div class="form-group col-md-4">
                        <label for="{{ form.hours.id_for_label }}">Hours</label>
                        {{ form.hours|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="{{ form.implementer.id_for_label }}">Implementer</label>
                        {{ form.implementer|add_class:"form-control" }}
                    </div>
                    <div class="form-group col-md-4">
                        <label for="{{ form.creator.id_for_label }}">Creator</label>
                        {{ form.creator|add_class:"form-control" }}
                    </div>
                    <div class="form-group col-md-4">
                        <label for="{{ form.project.id_for_label }}">Project</label>
                        {{ form.project|add_class:"form-control" }}
                    </div>
                </div>
                <br>
                <button class="btn btn-secondary btn-lg btn-block" type="submit">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

time_tracker/templates/tracker/task/task_info.html
{% extends 'tracker/tracker_home.html' %}

{% load static %}
{% load widget_tweaks %}

{% block title %}Task {{ task.subject }} for {{ task.project.name }}{% endblock %}

{% block brdc-links %}
    <li class="breadcrumb-item"><a href="{% url 'homepage' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'tracker-home' %}">Tracker</a></li>
    <li class="breadcrumb-item"><a href="{% url 'project-info' slug=task.project.slug %}">{{ task.project.name }}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">{{ task.subject }}</li>
{% endblock %}

{% block content %}
    <h1 class="h2">{{ task.subject }}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            {% if user.is_superuser %}
                <a href="{% url 'task-create' slug=task.project.slug %}" class="btn btn-sm btn-outline-secondary">Create
                    new task</a>
            {% endif %}
            <a href="{% url 'task-edit' slug=task.project.slug task_id=task.id %}"
               class="btn btn-sm btn-outline-secondary">Edit task</a>
            <a href="{% url 'tracker-home' %}" class="btn btn-sm btn-outline-secondary">Go back to tracker</a>
        </div>
    </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <div class="card-body">
                <h5 class="card-title">Add time</h5>
                {% if f_time.errors %}
                    {% for field in f_time %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in f_time.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    {% for hidden_field in f_time.hidden_fields %}
                        {{ hidden_field }}
                    {% endfor %}
                    {% render_field f_time.task hidden=hidden %}
                    {% render_field f_time.user hidden=hidden %}
                    <div class="form-group">
                        <label for="{{ f_time.hours.id_for_label }}">Hours</label>
                        {{ f_time.hours|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ f_time.comment.id_for_label }}">Comment</label>
                        {{ f_time.comment|add_class:"form-control"|attr:"rows: 2" }}
                    </div>
                    <button class="btn btn-outline-secondary" type="submit">Add</button>
                </form>
                <br>
                <ul class="list-group">
                    {% for time in time_list %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            {{ time.comment }}
                            <span class="badge badge-primary badge-pill">{{ time.hours }} h</span>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-md-7">
            <h5 class="card-title">Description</h5>
            <div class="alert alert-light" role="alert" style="text-align: justify;">
                {{ task.description|safe }}
            </div>
            <hr>
            <div class="card-body">
                <h5 class="card-title">Comments</h5>
                {% if f_comment.errors %}
                    {% for field in f_comment %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in f_comment.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    {% for hidden_field in f_comment.hidden_fields %}
                        {{ hidden_field }}
                    {% endfor %}
                    {% render_field f_comment.task hidden=hidden %}
                    {% render_field f_comment.author hidden=hidden %}
                    <div class="form-group">
                        <label for="{{ f_comment.comment.id_for_label }}">Comment</label>
                        {{ f_comment.comment|add_class:"form-control"|attr:"rows: 5" }}
                    </div>
                    <button class="btn btn-secondary btn-lg btn-block" type="submit">Add comment</button>
                </form>
            </div>
            <div class="list-group" style="padding: 1rem;">
                {% for comment in comments %}
                    <a href="#" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <small>{{ comment.createdAt|date:"d-m-Y" }} {{ comment.createdAt|time:"H:i" }}</small>
                        </div>
                        <p class="mb-1">{{ comment.comment|safe }}</p>
                        <small>Author: <b>{{ comment.author }}</b></small>
                    </a>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-3">
            <div class="list-group" style="padding-bottom: 1rem;">
                <a href="#" class="list-group-item list-group-item-action" style="border: none;">
                    <div class="d-flex w-100 justify-content-between">
                        <small>{{ task.date_start|date:"d-m-Y" }} to {{ task.date_stop|date:"d-m-Y" }}<br><br>
                            Hours: {{ task.hours }}</small>
                    </div>
                    <br>
                    <small>Type: <b>{{ task.get_kind_display }}</b><br>Priority:
                        <b>{{ task.get_priority_display }}</b></small><br>
                    <small>Creator: <b>{{ task.creator }}</b><br>Implementor:
                        <b>{{ task.implementer.user }}</b></small>
                </a>
            </div>
            <br>
            <h5 class="card-title text-center">Spent time: {{ spent_time }} hours</h5>

        </div>
    </div>
{% endblock %}