accounts/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='log-in'),
    path('logout/', views.logout, name='log-out'),
    path('user/register/step-1/', views.register_step_1, name='register-step-1'),
    path('user/register/step-2/<int:user_id>', views.register_step_2, name='register-step-2'),
    path('users/', views.user_list, name='user-list'),
    # path('profile/', views.profile, name='user-profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ttr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('time_tracker.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tinymce/', include('tinymce.urls')),

]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from time_tracker.models import Developer
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class DeveloperCreationForm(forms.ModelForm):
    class Meta:
        model = Developer
        fields = '__all__'

    # def clean_user(self):
    #     return self.cleaned_data['user']

    def clean_avatar(self):
        return self.cleaned_data['avatar']


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'is_active',
            'is_staff',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        user.save()
        return user

accounts/views.py
from django.contrib import auth
from time_tracker.models import Developer, Log, Project, Task
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import user_passes_test
from accounts.forms import DeveloperCreationForm, RegistrationForm


def login(request):
    args = dict()
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            args['profile'] = user
            return redirect('/', args)
        else:
            args['login_error'] = 'User not found!'
            return render(request, 'login/login.html', args)
    else:
        return render(request, 'login/login.html', args)


def logout(request):
    auth.logout(request)
    return redirect('homepage')


@user_passes_test(lambda u: u.is_superuser, login_url='/')
def register_step_1(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('accounts:register-step-2', user_id=user.pk)
        return render(request, 'register/register_1.html', {'form': form})
    else:
        form = RegistrationForm()
        return render(request, 'register/register_1.html', {'form': form})


@user_passes_test(lambda u: u.is_superuser, login_url='/')
def register_step_2(request, user_id):
    if request.method == 'POST':
        form = DeveloperCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('accounts:user-list')
        return render(request, 'register/register_2.html', {'form': form})
    else:
        form = DeveloperCreationForm(initial={'user': User.objects.get(id=user_id)})
        return render(request, 'register/register_2.html', {'form': form})


@user_passes_test(lambda u: u.is_superuser, login_url='/')
def user_list(request):
    users = Developer.objects.all()
    return render(request, 'list/index.html', {'users': users})


# def profile(request):
#     if request.user.is_superuser:
#         projects = Project.objects.all()
#     else:
#         dev = Developer.objects.get(user__username=request.user.username)
#         projects_id = Task.objects.filter(implementer=dev).all()
#         projects = Project.objects.filter(pk__in=[x.project.pk for x in projects_id])
#
#     return render(request, 'profile/index.html', {'projects': projects})

accounts/templates/list/index.html
{% extends 'tracker/tracker_home.html' %}

{% block title %}User list{% endblock %}

{% block brdc-links %}
    <li class="breadcrumb-item"><a href="{% url 'homepage' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'tracker-home' %}">Tracker</a></li>
    <li class="breadcrumb-item active" aria-current="page">User list</li>
{% endblock %}

{% block content %}
    <h1 class="h2">User list</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a href="{% url 'accounts:register-step-1' %}" class="btn btn-sm btn-outline-secondary">Create new developer</a>
            <a href="{% url 'tracker-home' %}" class="btn btn-sm btn-outline-secondary">Go back to tracker</a>
        </div>
    </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th>#</th>
                <th>Username</th>
                <th>Avatar</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Email</th>
                <th>Date of birth</th>
                <th>Position</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <th>{{ forloop.counter }}</th>
                    <td>{{ user.user.username }}</td>
                    <td><img alt="" src="/accounts/media/{{ user.avatar }}" width="150px"></td>
                    <td>{{ user.user.first_name }}</td>
                    <td>{{ user.user.last_name }}</td>
                    <td>{{ user.user.email }}</td>
                    <td>{{ user.birth_date|date:"Y-m-d" }}</td>
                    <td>{{ user.position }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}