accounts/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='log-in'),
    path('logout/', views.logout, name='log-out'),
    path('user/register/step-1/', views.register_step_1, name='register-step-1'),
    path('user/register/step-2/<int:user_id>', views.register_step_2, name='register-step-2'),
    path('users/', views.user_list, name='user-list'),
    # path('profile/', views.profile, name='user-profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

time_tracker/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    path('', HomeView.as_view(), name='homepage'),
    path('tracker/', TrackerHomeView.as_view(), name='tracker-home'),
    path('tracker/time-log', TimeLogListView.as_view(), name='time-log-list'),
    path('tracker/project/create', ProjectCreateView.as_view(), name='project-create'),
    path('tracker/project/<slug:slug>', ProjectDetailView.as_view(), name='project-info'),
    path('tracker/project/<slug:slug>/edit', ProjectUpdateView.as_view(), name='project-edit'),
    path('tracker/project/<slug:slug>/task/create', TaskCreateView.as_view(), name='task-create'),
    path('tracker/project/<slug:slug>/task/<int:task_id>', TaskDetailView.as_view(), name='task-info'),
    path('tracker/project/<slug:slug>/task/<int:task_id>/edit', TaskUpdateView.as_view(), name='task-edit'),
]

ttr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('time_tracker.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tinymce/', include('tinymce.urls')),

]

time_tracker/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from tinymce import models as tinymce_models
from django.template.defaultfilters import slugify


def get_image_path(instance, filename):
    return os.path.join('user_avatars', str(instance.user.id), filename)


class Developer(models.Model):
    user = models.ForeignKey(
        User,
        null=True,
        on_delete=models.SET_NULL
    )
    birth_date = models.DateField(null=True, blank=True)
    position = models.CharField(max_length=128, blank=True)
    avatar = models.FileField(upload_to=get_image_path, blank=True)

    def __str__(self):
        return self.user.username


class Project(models.Model):
    name = models.CharField(max_length=128)
    description = tinymce_models.HTMLField()
    slug = models.SlugField(max_length=192)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Project, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Task(models.Model):
    PRIORITY_TYPE = (
        ('N', 'Normal'),
        ('H', 'High'),
        ('U', 'Urgent')
    )

    TASK_TYPE = (
        ('F', 'Feature'),
        ('B', 'Bug'),
    )
    subject = models.CharField(max_length=128)
    description = tinymce_models.HTMLField()
    date_start = models.DateField()
    date_stop = models.DateField()
    kind = models.CharField(max_length=1, choices=TASK_TYPE, default='F')
    priority = models.CharField(max_length=1, choices=PRIORITY_TYPE, default='N')
    hours = models.FloatField()
    implementer = models.ForeignKey(Developer, null=True, on_delete=models.SET_NULL, related_name='task_implementer')
    creator = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='task_creator')
    project = models.ForeignKey(Project, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.subject


class Comment(models.Model):
    comment = models.TextField()
    createdAt = models.DateTimeField(auto_now_add=True, null=True)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    task = models.ForeignKey(Task, null=True, on_delete=models.SET_NULL)


class Log(models.Model):
    hours = models.FloatField()
    comment = models.TextField()
    task = models.ForeignKey(Task, null=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

time_tracker/forms.py
from django import forms
from .models import Comment, Log, Task, Project


class AddCommentToTaskForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'


class AddTimeToTaskForm(forms.ModelForm):
    class Meta:
        model = Log
        fields = '__all__'


class CreateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('name', 'description')


class EditTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EditTaskForm, self).__init__(*args, **kwargs)
        self.fields['creator'].widget.attrs['disabled'] = True
        self.fields['creator'].required = False

    def clean_creator(self):
        if self.instance and self.instance.pk:
            return self.instance.creator
        else:
            return self.cleaned_data['creator']

time_tracker/views.py
from django.conf import settings
from django.dispatch import receiver
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, redirect, get_object_or_404
from time_tracker.models import Project, Task, Log, Developer, Comment
from django.views.generic import View, TemplateView, ListView, CreateView, DetailView, UpdateView
from time_tracker.forms import CreateTaskForm, EditTaskForm, AddTimeToTaskForm, AddCommentToTaskForm, ProjectForm


@receiver(pre_save, sender=Task)
def task_send_message(instance, sender, **kwargs):
    try:
        old = sender.objects.get(pk=instance.pk)
    except sender.DoesNotExist:
        pass
    else:
        html = get_template('email/email.html')
        d = {'old': old, 'new': instance}

        subject, from_email, to = 'Changed task', settings.EMAIL_HOST_USER, [old.creator.email,
                                                                             instance.implementer.user.email]
        html_content = html.render(d)
        msg = EmailMultiAlternatives(subject, "text_content", from_email, to)
        msg.attach_alternative(html_content, "text/html")
        msg.send()


class HomeView(TemplateView):
    template_name = 'index.html'


class TimeLogListView(ListView):
    model = Log
    template_name = 'list/log_index.html'
    context_object_name = 'logs'


class TrackerHomeView(View):

    def get(self, request, *args, **kwargs):
        if request.user.is_superuser:
            projects = Project.objects.all()
        else:
            dev = Developer.objects.get(user__username=request.user.username)
            projects_id = Task.objects.filter(implementer=dev).all()
            projects = Project.objects.filter(pk__in=[x.project.pk for x in projects_id])

        return render(request, 'tracker/tracker_home.html', {'projects': projects})


class ProjectDetailView(DetailView):
    model = Project
    template_name = 'tracker/project/project_info.html'
    context_object_name = 'project'
    calc_time = time = 0

    def set_time(self, tasks):
        for task in tasks:
            self.calc_time += task.hours
            for l in Log.objects.filter(task_id=task.id):
                self.time += float(l.hours)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tasks = Task.objects.filter(project__slug=self.object.slug)
        self.set_time(tasks)
        context['tasks'] = tasks
        context['hours'] = self.time
        context['caclTime'] = self.calc_time
        return context


class TaskDetailView(DetailView):
    model = Task
    template_name = 'tracker/task/task_info.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Task, id=self.kwargs.get('task_id'))

    def post(self, request, *args, **kwargs):
        f_time = AddTimeToTaskForm(request.POST, prefix='time')
        f_comment = AddCommentToTaskForm(request.POST, prefix='comment')

        if f_time.is_valid():
            f_time.save()
            return redirect('task-info', slug=self.kwargs.get('slug'), task_id=self.kwargs.get('task_id'))

        if f_comment.is_valid():
            f_comment.save()
            return redirect('task-info', slug=self.kwargs.get('slug'), task_id=self.kwargs.get('task_id'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        spent_time = 0
        project = Project.objects.get(slug=self.kwargs.get('slug'))
        comments = Comment.objects.filter(task_id=self.kwargs.get('task_id')).order_by('-createdAt')
        time = Log.objects.filter(task_id=self.kwargs.get('task_id'))
        for t in time:
            spent_time += t.hours

        context['f_time'] = AddTimeToTaskForm(
            initial={'task': self.get_object(), 'user': User.objects.get(username=self.request.user)},
            prefix='time')
        context['f_comment'] = AddCommentToTaskForm(
            initial={'task': self.get_object(), 'author': User.objects.get(username=self.request.user)},
            prefix='comment')
        context['project'] = project
        context['comments'] = comments
        context['time_list'] = time
        context['spent_time'] = spent_time

        return context


class TaskUpdateView(UpdateView):
    model = Task
    template_name = 'tracker/task/edit_task_info.html'
    form_class = EditTaskForm

    def get_object(self, queryset=None):
        return get_object_or_404(Task, id=self.kwargs.get('task_id'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = Project.objects.get(slug=self.kwargs.get('slug'))
        return context


class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectForm
    template_name = 'tracker/project/create_project.html'
    success_url = reverse_lazy('tracker-home')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(ProjectCreateView, self).dispatch(*args, **kwargs)


class ProjectUpdateView(UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = 'tracker/project/edit_project.html'
    success_url = reverse_lazy('tracker-home')

    def get_object(self, queryset=None):
        return get_object_or_404(Project, slug=self.kwargs.get('slug'))

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(ProjectUpdateView, self).dispatch(*args, **kwargs)


class TaskCreateView(CreateView):
    model = Task
    form_class = CreateTaskForm
    template_name = 'tracker/task/create_task.html'
    success_url = reverse_lazy('tracker-home')

    def get_initial(self):
        project = Project.objects.get(slug=self.kwargs.get('slug'))
        return {'project': project, 'creator': self.request.user}

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(TaskCreateView, self).dispatch(*args, **kwargs)

time_tracker/templates/tracker/tracker_home.html
{% extends 'base.html' %}

{% block title %}Time tracker{% endblock %}

{% block body %}
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Time Tracker</a>
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                {% if user.is_authenticated %}
                    <a href="{% url 'accounts:log-out' %}" class="nav-link">Log out</a>
                {% else %}
                    <a href="{% url 'accounts:log-in' %}" class="nav-link">Log In</a>
                {% endif %}
            </li>
        </ul>
    </nav>
    <div class="container-fluid" style="margin-top: 3rem;">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <ul class="nav flex-column text-center">
                        <li class="card-body">
                            <svg class="bd-placeholder-img rounded-circle" width="140" height="140"
                                 xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false"
                                 role="img" aria-label="Placeholder: 140x140"><title>Avatar</title>
                                <rect width="100%" height="100%" fill="#777"></rect>
                                <text x="50%" y="50%" fill="#777" dy=".3em">140x140</text>
                            </svg>
                            <h2>{{ request.user }}</h2>
                            <hr>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'tracker-home' %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                     fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                     stroke-linejoin="round" class="feather feather-file-text">
                                    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                                    <polyline points="14 2 14 8 20 8"></polyline>
                                    <line x1="16" y1="13" x2="8" y2="13"></line>
                                    <line x1="16" y1="17" x2="8" y2="17"></line>
                                    <polyline points="10 9 9 9 8 9"></polyline>
                                </svg>
                                Tracker
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'time-log-list' %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                     fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                     stroke-linejoin="round" class="feather feather-file-text">
                                    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                                    <polyline points="14 2 14 8 20 8"></polyline>
                                    <line x1="16" y1="13" x2="8" y2="13"></line>
                                    <line x1="16" y1="17" x2="8" y2="17"></line>
                                    <polyline points="10 9 9 9 8 9"></polyline>
                                </svg>
                                Time log
                            </a>
                        </li>
                    </ul>
                    <hr>
                </div>
            </nav>
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb" style="background-color: #f8f9fa;">
                        {% block brdc-links %}
                            <li class="breadcrumb-item"><a href="{% url 'homepage' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Tracker</li>
                        {% endblock %}
                    </ol>
                </nav>
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    {% block content %}
                        <h1 class="h2">Available projects</h1>
                        <div class="btn-toolbar mb-2 mb-md-0">
                            <div class="btn-group mr-2">
                                {% if user.is_superuser %}
                                    <a href="{% url 'project-create' %}" class="btn btn-sm btn-outline-secondary">Create
                                        project</a>
                                    <a href="{% url 'accounts:user-list' %}" class="btn btn-sm btn-outline-secondary">User list</a>
                                {% endif %}
                            </div>
                        </div>
                        </div>
                        {% if projects %}
                            <div class="card-deck text-center">
                                {% for project in projects %}
                                    <div class="card mb-4 box-shadow">
                                        <div class="card-header">
                                            <h4 class="my-0 font-weight-normal">{{ project.name }}</h4>
                                        </div>
                                        <div class="card-body">
                                            <h1 class="card-title pricing-card-title">Count
                                                tasks: {{ project.task_set.count }}</h1>
                                            <p>{{ project.description|safe|truncatechars:32 }}</p>
                                            <a href="{% url 'project-info' slug=project.slug %}"
                                               class="btn btn-secondary btn-lg btn-block">More</a>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        {% else %}
                            <div class="alert alert-warning" role="alert">
                                You have not projects. Please, ask administrator.
                            </div>
                        {% endif %}

                        {#                <h2>Section title</h2>#}
                        {#                <div class="table-responsive">#}
                        {#                    <table class="table table-striped table-sm"></table>#}
                        {#                </div>#}
                    {% endblock %}
            </main>
        </div>
{% endblock %}